apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-php
  template:
    metadata:
      labels:
        app: dev-php
    spec:
      containers:
        - name: dev-php
          image: dev-php:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: php-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              value: root


          volumeMounts:
            - mountPath: "/var/www/html"
              name: php-sources
      volumes:
        - name: php-sources
          hostPath:
            path: /mnt/volumes/src/dev-php
            type: DirectoryOrCreate

