apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEXTAUTH_URL
              value: https://{{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.subdomain .Values.global.domain) }}

          {{ if .Values.runDev }}
          command: ["bash", "-c"]
          args:
            - "cd /workspace/app && npm run dev"
          {{ end }}

          volumeMounts:
            - name: workspace-volume
              mountPath: {{ .Values.volume.mountPath }}

      volumes:
        - name: workspace-volume
          hostPath:
            path: {{ .Values.volume.hostPath }}
            type: DirectoryOrCreate
