apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-dev-js
spec:
  selector:
    app: dev-js
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8080
      targetPort: 8080
      name: http-2
    - port: 3000
      targetPort: 3000
      name: node-dev
