apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0LXJvb3QtcGFzcw==   # "secret-root-pass"
  MYSQL_USER: dXNlcg==                            # "user"
  MYSQL_PASSWORD: c2VjcmV0LXVzZXItcGFzcw==        # "secret-user-pass"
