  loki:
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: filesystem  # Utiliser le système de fichiers local
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache  # ✅ Conserve cache_location, mais supprime shared_store
      filesystem:
        directory: /var/loki  # ✅ Répertoire local où stocker les logs

    ingester:
      chunk_encoding: snappy
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 1
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true

  deploymentMode: SimpleScalable

  backend:
    replicas: 1
  read:
    replicas: 1
  write:
    replicas: 2 # To ensure data durability with replication

  # Enable minio for storage
  minio:
    enabled: true

  gateway:
    service:
      type: LoadBalancer