apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-env-prometheus-mysql-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-mysql-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: mysql-exporter
      interval: 30s
