apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": "post-install, post-upgrade"
    {{- range $key, $value := .Values.global.ingress.annotationsLetsEncrypt }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.subdomain .Values.global.domain) }}
  # default behavior is to use the secret ; but we store cert in a volume
  # secretName: letsencrypt-cert
  rules:
  - host: {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.subdomain .Values.global.domain) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Namespace }}-grafana
            port:
              number: 80

