apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
    - name: node-dev
      port: 3000
      targetPort: 3000


