apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # ⚠️ Seulement pour le dev avec K3d (remplace par un stockage cloud en prod)
    path: "/mnt/volumes/mariadb"
