apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-pod-manager
  namespace: tools

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cron-pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-pod-manager-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tools
roleRef:
  kind: ClusterRole
  name: cron-pod-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  serviceAccountName: cron-pod-manager
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - name: cron
          image: cron:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

