global:
  domain: "k8s.home3.jlb.ninja"
  ingress:
    enabled: true
    annotationsLetsEncrypt:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "le"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"